name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: pre-commit/action@v2.0.3
=======
      - uses: pre-commit/action@v2.0.3
>>>>>>> 98eaa55 (add workflow files)
=======
      - uses: pre-commit/action@v2.0.3
>>>>>>> ce41081 (fix end of files)
